"""empty message

Revision ID: 14b431199dfa
Revises: 0b43d53b6ef6
Create Date: 2021-06-28 19:42:14.182924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b431199dfa'
down_revision = '0b43d53b6ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorite', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    # ### end Alembic commands ###
