"""empty message

Revision ID: b408c380a583
Revises: 2724db9c5dc6
Create Date: 2021-06-24 18:15:34.257705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b408c380a583'
down_revision = '2724db9c5dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('username', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'username')
    # ### end Alembic commands ###
