"""empty message

Revision ID: fa17a5f43149
Revises: 14b431199dfa
Create Date: 2021-07-07 17:17:18.029247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa17a5f43149'
down_revision = '14b431199dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_entity_id_key', 'favorite', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('favorite_entity_id_key', 'favorite', ['entity_id'])
    # ### end Alembic commands ###
