"""empty message

Revision ID: fcb588bce831
Revises: a74564d2c897
Create Date: 2021-06-23 21:33:37.274629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb588bce831'
down_revision = 'a74564d2c897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id'),
    sa.UniqueConstraint('entity_type'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey'),
    sa.UniqueConstraint('entity_id', name='favorites_entity_id_key'),
    sa.UniqueConstraint('entity_type', name='favorites_entity_type_key'),
    sa.UniqueConstraint('name', name='favorites_name_key')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###
